name: Docker Image CI

on:
  push:
    branches: [ "master" ]
permissions:
  id-token: write
  contents: read
  
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Installing CLI-beta for OIDC
      run: |
              python3 -m pip install -q --upgrade pip
              pip install azure-cli
    - name: Azure Login
      uses: Azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
    - name: 'Run az commands'
      run: |
          az account show
          az group list
          pwd 
    - name: 'Run curl for token'
      run: |
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          curl -vs -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange"
