on:
  workflow_call:
jobs:
  getjwt:
    runs-on: self-hosted
    steps:
    - name: 'Run curl for token'
      run: |
          echo "$ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          echo "$ACTIONS_ID_TOKEN_REQUEST_URL"
          output=$(curl -vs -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | base64 -w0)
          echo $output
